<?php
/**
 * @file
 * osha.features.user_permission.inc
 */

/**
 * Implements hook_user_default_permissions().
 */
function osha_user_default_permissions() {
  $permissions = array();

  // Exported permission: 'access news feeds'.
  $permissions['access news feeds'] = array(
    'name' => 'access news feeds',
    'roles' => array(
      'administrator' => 'administrator',
      'anonymous user' => 'anonymous user',
      'authenticated user' => 'authenticated user',
    ),
    'module' => 'aggregator',
  );

  return $permissions;
}
