<?php
/**
 * @file
 * Code for the Job vacancies feature.
 */

include_once 'osha_job_vacancies.features.inc';

define('OSHA_JOB_VACANCIES_CONTENT_TYPE_JOB_VACANCIES', 'job_vacancies');

/**
 * Implements hook_post_features_enable_feature().
 *
 * {@inheritdoc}
 */
function osha_job_vacancies_post_features_enable_feature($component) {
  // After the field_instance ...
  if ($component == 'variable') {
    menu_rebuild();
    drupal_static_reset();
    if ($role = user_role_load_by_name('administrator')) {
      $permissions = array(
        'create job_vacancies content',
        'edit own job_vacancies content',
        'edit any job_vacancies content',
        'delete own job_vacancies content',
        'delete any job_vacancies content',
      );
      user_role_grant_permissions($role->rid, $permissions);
    }
  }
}

function osha_job_vacancies_post_features_revert($component) {
  // reset position of menu items
  $parent = db_select('menu_links', 'm')
    ->fields('m')
    ->condition('link_title', 'Careers')
    ->condition('menu_name', 'main-menu')
    ->execute()
    ->fetchAssoc();
  if (!$parent['has_children']) {
    db_update('menu_links')
      ->fields(array('has_children' => 1, 'customized' => 1))
      ->condition('link_title', 'Careers')
      ->condition('menu_name', 'main-menu')
      ->execute();
    db_update('menu_links')
      ->fields(array(
        'plid' => $parent['mlid'],
        'depth' => 4,
        'customized' => 1,
        'p1' => $parent['p1'],
        'p2' => $parent['p2'],
        'p3' => $parent['p3']
      ))
      ->expression('p4', 'mlid')
      ->condition('link_path', array('jobs_archive', 'open_job_vacancies', 'ongoing_job_vacancies', 'shortlisted_job_vacancies'), 'IN')
      ->condition('depth', 1)
      ->condition('menu_name', 'main-menu')
      ->execute();
  }
}

/**
 * Implements hook_node_validate().
 *
 * {@inheritdoc}
 */
function osha_job_vacancies_node_validate($node, $form, &$form_state) {
  $values = $form_state['values'];
  if ($node->type == 'job_vacancies' &&
      !empty($values['field_job_vacancies_deadline'][LANGUAGE_NONE][0]['value']) &&
      !empty($values['field_publication_date'][LANGUAGE_NONE][0]['value'])
  ) {
    $deadline_date = strtotime($values['field_job_vacancies_deadline'][LANGUAGE_NONE][0]['value']);
    $publication_date = strtotime($values['field_publication_date'][LANGUAGE_NONE][0]['value']);
    // Assume that all fields use the same timezone handling settings.
    if ($deadline_date < $publication_date) {
      form_set_error('field_job_vacancies_deadline', 'Deadline must be after the publication date');
    }
    if (!empty($values['field_expiration_date'][LANGUAGE_NONE][0]['value'])) {
      $expiration_date = strtotime($values['field_expiration_date'][LANGUAGE_NONE][0]['value']);
      if ($expiration_date < $deadline_date) {
        form_set_error('field_expiration_date', 'Item must expire after the deadline');
      }
    }
  }
}

function osha_job_vacancies_workbench_access_node_element_alter(&$element, $form_state, $active) {
  if (isset($form_state['build_info']['form_id']) && $form_state['build_info']['form_id'] == 'job_vacancies_node_form' ) {
    // CW-865 default value for Section
    $element['#required'] = FALSE;
    foreach ($element['#options'] as $key=>$option) {
      if (preg_match('/^[-\\s]*Careers/', $option)) {
        $element['#default_value'] = $key;
        break;
      }
    }
  }
}


/**
 * Implements hook_form_alter().
 */
function osha_job_vacancies_form_job_vacancies_node_form_alter(&$form) {
  if (empty($form['nid']['#value']) ||
    (isset($form['body']['#language']) &&
      empty($form['body'][$form['body']['#language']][0]['#default_value']))) {
    // CW-859 disable body for new vacancies and for existing nodes with empty body
    $form['body']['#access'] = FALSE;
  }
}
