<?php
/**
 * @file
 * Code for the Job vacancies feature.
 */

include_once 'osha_job_vacancies.features.inc';

define('OSHA_JOB_VACANCIES_CONTENT_TYPE_JOB_VACANCIES', 'job_vacancies');

/**
 * Implements hook_post_features_enable_feature().
 *
 * {@inheritdoc}
 */
function osha_job_vacancies_post_features_enable_feature($component) {
  // After the field_instance ...
  if ($component == 'variable') {
    menu_rebuild();
    drupal_static_reset();
    if ($role = user_role_load_by_name('administrator')) {
      $permissions = array(
        'create job_vacancies content',
        'edit own job_vacancies content',
        'edit any job_vacancies content',
        'delete own job_vacancies content',
        'delete any job_vacancies content',
      );
      user_role_grant_permissions($role->rid, $permissions);
    }
  }
}

function osha_job_vacancies_post_features_revert($component) {
  // reset position of menu items
  $parent = db_select('menu_links', 'm')
    ->fields('m')
    ->condition('link_title', 'Careers')
    ->condition('menu_name', 'main-menu')
    ->execute()
    ->fetchAssoc();
  if (!$parent['has_children']) {
    db_update('menu_links')
      ->fields(array('has_children' => 1, 'customized' => 1))
      ->condition('link_title', 'Careers')
      ->condition('menu_name', 'main-menu')
      ->execute();
    db_update('menu_links')
      ->fields(array(
        'plid' => $parent['mlid'],
        'depth' => 4,
        'customized' => 1,
        'p1' => $parent['p1'],
        'p2' => $parent['p2'],
        'p3' => $parent['p3']
      ))
      ->expression('p4', 'mlid')
      ->condition('link_path', array('jobs_archive', 'open_job_vacancies', 'ongoing_job_vacancies', 'shortlisted_job_vacancies'), 'IN')
      ->condition('depth', 1)
      ->condition('menu_name', 'main-menu')
      ->execute();
  }
}
