<?php
/**
 * @file
 * Code for the Osha Menu feature.
 */

include_once 'osha_menu.features.inc';
define('OSHA_MENU_RENDER_IMG_VAR_NAME', 'render_menu_image');

/**
 * Implements hook_block_configure_alter().
 */
function osha_menu_menu_block_configure_form_alter(&$form, &$form_state) {
  $form['osha_menu_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('OSHA Menu Settings'),
  );
  $form['osha_menu_settings'][OSHA_MENU_RENDER_IMG_VAR_NAME] = array(
    '#type' => 'checkbox',
    '#title' => t('Render Menu Image.'),
    '#default_value' => variable_get('menu_block_' .
      $form_state['values']['delta'] . '_' . OSHA_MENU_RENDER_IMG_VAR_NAME, 0),
    '#description' => t('Render Image in menu'),
  );
}

/**
 * Implements hook_menu_block_block_save().
 */
function osha_menu_menu_block_block_save($delta, $form) {
  variable_set('menu_block_' . $delta . '_' . OSHA_MENU_RENDER_IMG_VAR_NAME,
    $form[OSHA_MENU_RENDER_IMG_VAR_NAME]);
}

/**
 * Implements hook_menu_block_block_delete().
 */
function osha_menu_menu_block_block_delete($form, $form_state) {
  $delta = $form_state['values']['delta'];
  variable_del('menu_block_' . $delta . '_' . OSHA_MENU_RENDER_IMG_VAR_NAME);
}

/**
 * Implements hook_menu_breadcrumb_alter().
 */
function osha_menu_breadcrumb_alter(&$active_trail, $item) {
  // Remove parent items from breadcrumb if same title or path as child
  // (useful when have <nolink> ex: Emerging Risks/Emerging Risks).
  foreach ($active_trail as $idx => $link) {
    if (!empty($link['link_title']) && !empty($active_trail[$idx + 1]['link_title'])) {
      if (($link['link_title'] == $active_trail[$idx + 1]['link_title'])) {
        unset($active_trail[$idx]);
      }
    }
  }
}
