<?php
/**
 * @file
 * osha_highlight.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function osha_highlight_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_aditional_resources'
  $field_bases['field_aditional_resources'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_aditional_resources',
    'foreign keys' => array(
      'node' => array(
        'columns' => array(
          'target_id' => 'nid',
        ),
        'table' => 'node',
      ),
    ),
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'sort' => array(
          'type' => 'none',
        ),
        'target_bundles' => array(
          'external_url' => 'external_url',
          'file' => 'file',
          'flickr' => 'flickr',
          'news' => 'news',
          'press_release' => 'press_release',
          'publication' => 'publication',
          'slideshare' => 'slideshare',
          'youtube' => 'youtube',
        ),
      ),
      'target_type' => 'node',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  return $field_bases;
}
