<?php
/**
 * @file
 * osha_taxonomy.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function osha_taxonomy_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => '1: Anticipating change',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '00cf9383-d3f2-4220-a8a2-42a0d4b4a33b',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'anticipating_change',
          'format' => NULL,
          'safe_value' => 'anticipating_change',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 1,
          'format' => NULL,
          'safe_value' => 1,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '1: Anticipating change',
          'format' => NULL,
          'safe_value' => '1: Anticipating change',
        ),
      ),
    ),
    'name_original' => '1: Anticipating change',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 8,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '3: Tools for OSH management',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '08e11f8b-4122-4e6e-83cb-2e0b3c06d082',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'tools_for_osh_management',
          'format' => NULL,
          'safe_value' => 'tools_for_osh_management',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 1,
          'format' => NULL,
          'safe_value' => 1,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '3: Tools for OSH management',
          'format' => NULL,
          'safe_value' => '3: Tools for OSH management',
        ),
      ),
    ),
    'name_original' => '3: Tools for OSH management',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 17,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '2.1. European Survey of Enterprises on New & Emerging Risks (ESENER)',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2a207a55-e8be-4910-9b9a-47995c11e39c',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'facts_and_figures_1',
          'format' => NULL,
          'safe_value' => 'facts_and_figures_1',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '2.1. European Survey of Enterprises on New & Emerging Risks (ESENER)',
          'format' => NULL,
          'safe_value' => '2.1. European Survey of Enterprises on New &amp; Emerging Risks (ESENER)',
        ),
      ),
    ),
    'name_original' => '2.1. European Survey of Enterprises on New & Emerging Risks (ESENER)',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 12,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => 'e9fa57e4-b0c3-476b-898c-176ae24d6062',
    ),
  );
  $terms[] = array(
    'name' => '7.1. Finance & Accounting',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2b5014f8-9d88-489d-9f16-75cb35fadb09',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'governance_1',
          'format' => NULL,
          'safe_value' => 'governance_1',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '7.1. Finance & Accounting',
          'format' => NULL,
          'safe_value' => '7.1. Finance &amp; Accounting',
        ),
      ),
    ),
    'name_original' => '7.1. Finance & Accounting',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 33,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => 'f77ff1e1-cccc-4f56-b470-ad638467b135',
    ),
  );
  $terms[] = array(
    'name' => '5: Networking knowledge',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '341c68a0-184a-4c11-8789-178251c02872',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'networking_knowledge',
          'format' => NULL,
          'safe_value' => 'networking_knowledge',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 1,
          'format' => NULL,
          'safe_value' => 1,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '5: Networking knowledge',
          'format' => NULL,
          'safe_value' => '5: Networking knowledge',
        ),
      ),
    ),
    'name_original' => '5: Networking knowledge',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 25,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '2.5. Costs and benefits of OSH',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3cca98a5-f928-4543-a290-e6c009efcb1e',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'facts_and_figures_5',
          'format' => NULL,
          'safe_value' => 'facts_and_figures_5',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '2.5. Costs and benefits of OSH',
          'format' => NULL,
          'safe_value' => '2.5. Costs and benefits of OSH',
        ),
      ),
    ),
    'name_original' => '2.5. Costs and benefits of OSH',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 16,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => 'e9fa57e4-b0c3-476b-898c-176ae24d6062',
    ),
  );
  $terms[] = array(
    'name' => '4: Raising awareness',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '57c7ff22-5cd8-49c4-8789-262d2a3453bd',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'raising_awareness',
          'format' => NULL,
          'safe_value' => 'raising_awareness',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 1,
          'format' => NULL,
          'safe_value' => 1,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '4: Raising awareness',
          'format' => NULL,
          'safe_value' => '4: Raising awareness',
        ),
      ),
    ),
    'name_original' => '4: Raising awareness',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 20,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '5.2. Other networking knowledge actions',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '68ed2a83-8327-4c9a-9a1d-c77cf9860cde',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'networking_knowledge_2',
          'format' => NULL,
          'safe_value' => 'networking_knowledge_2',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '5.2. Other networking knowledge actions',
          'format' => NULL,
          'safe_value' => '5.2. Other networking knowledge actions',
        ),
      ),
    ),
    'name_original' => '5.2. Other networking knowledge actions',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 27,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => '341c68a0-184a-4c11-8789-178251c02872',
    ),
  );
  $terms[] = array(
    'name' => '6: Networking and Corporate Communications',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6d67c342-6a54-409f-a512-9796ab5d2fc0',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'networking_and_corporate_communications',
          'format' => NULL,
          'safe_value' => 'networking_and_corporate_communications',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 1,
          'format' => NULL,
          'safe_value' => 1,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '6: Networking and Corporate Communications',
          'format' => NULL,
          'safe_value' => '6: Networking and Corporate Communications',
        ),
      ),
    ),
    'name_original' => '6: Networking and Corporate Communications',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 28,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '5.1 OSHwiki',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '724a92e2-016d-4611-bebc-11f3b09eaf64',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'networking_knowledge_1',
          'format' => NULL,
          'safe_value' => 'networking_knowledge_1',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '5.1 OSHwiki',
          'format' => NULL,
          'safe_value' => '5.1 OSHwiki',
        ),
      ),
    ),
    'name_original' => '5.1 OSHwiki',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 26,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => '341c68a0-184a-4c11-8789-178251c02872',
    ),
  );
  $terms[] = array(
    'name' => '2.3. OSH overview: Micro and small enterprises',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '745eb89c-b6a3-455e-94ae-3244e10df1e9',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'facts_and_figures_3',
          'format' => NULL,
          'safe_value' => 'facts_and_figures_3',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '2.3. OSH overview: Micro and small enterprises',
          'format' => NULL,
          'safe_value' => '2.3. OSH overview: Micro and small enterprises',
        ),
      ),
    ),
    'name_original' => '2.3. OSH overview: Micro and small enterprises',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 14,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => 'e9fa57e4-b0c3-476b-898c-176ae24d6062',
    ),
  );
  $terms[] = array(
    'name' => '3.2. Tool for implementing OSH solutions',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '777ac578-5ecf-4c08-bf2f-72ebe7b14871',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'tools_for_osh_management_2',
          'format' => NULL,
          'safe_value' => 'tools_for_osh_management_2',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '3.2. Tool for implementing OSH solutions',
          'format' => NULL,
          'safe_value' => '3.2. Tool for implementing OSH solutions',
        ),
      ),
    ),
    'name_original' => '3.2. Tool for implementing OSH solutions',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 19,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => '08e11f8b-4122-4e6e-83cb-2e0b3c06d082',
    ),
  );
  $terms[] = array(
    'name' => '2.2. OSH overview: Older workers',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7df1e54d-8ab2-45f8-a8db-def8330ece19',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'facts_and_figures_2',
          'format' => NULL,
          'safe_value' => 'facts_and_figures_2',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '2.2. OSH overview: Older workers',
          'format' => NULL,
          'safe_value' => '2.2. OSH overview: Older workers',
        ),
      ),
    ),
    'name_original' => '2.2. OSH overview: Older workers',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 13,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => 'e9fa57e4-b0c3-476b-898c-176ae24d6062',
    ),
  );
  $terms[] = array(
    'name' => '3.1. Online interactive Risk Assessment (OiRA) tool',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7f6e2e39-911c-4f0c-88fc-8eb42dc8f370',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'tools_for_osh_management_1',
          'format' => NULL,
          'safe_value' => 'tools_for_osh_management_1',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '3.1. Online interactive Risk Assessment (OiRA) tool',
          'format' => NULL,
          'safe_value' => '3.1. Online interactive Risk Assessment (OiRA) tool',
        ),
      ),
    ),
    'name_original' => '3.1. Online interactive Risk Assessment (OiRA) tool',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 18,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => '08e11f8b-4122-4e6e-83cb-2e0b3c06d082',
    ),
  );
  $terms[] = array(
    'name' => '6.2. Operational Networking',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8b9e5d84-e921-4b97-9ffe-04a509ca2d8f',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'networking_and_corporate_communications_2',
          'format' => NULL,
          'safe_value' => 'networking_and_corporate_communications_2',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '6.2. Operational Networking',
          'format' => NULL,
          'safe_value' => '6.2. Operational Networking',
        ),
      ),
    ),
    'name_original' => '6.2. Operational Networking',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 30,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => '6d67c342-6a54-409f-a512-9796ab5d2fc0',
    ),
  );
  $terms[] = array(
    'name' => '4.1. Healthy Workplace Campaign (HWC): Working together for risk prevention',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8f1f0efc-a820-4e0a-858f-0abefa0a78ab',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'raising_awareness_1',
          'format' => NULL,
          'safe_value' => 'raising_awareness_1',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '4.1. Healthy Workplace Campaign (HWC): Working together for risk prevention',
          'format' => NULL,
          'safe_value' => '4.1. Healthy Workplace Campaign (HWC): Working together for risk prevention',
        ),
      ),
    ),
    'name_original' => '4.1. Healthy Workplace Campaign (HWC): Working together for risk prevention',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 21,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => '57c7ff22-5cd8-49c4-8789-262d2a3453bd',
    ),
  );
  $terms[] = array(
    'name' => '1.1. Foresight of new and emerging OSH risks  associated with new technologies in green jobs',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '981044b4-313e-494c-abab-40e139c26244',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'anticipating_change_1',
          'format' => NULL,
          'safe_value' => 'anticipating_change_1',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '1.1. Foresight of new and emerging OSH risks  associated with new technologies in green jobs',
          'format' => NULL,
          'safe_value' => '1.1. Foresight of new and emerging OSH risks  associated with new technologies in green jobs',
        ),
      ),
    ),
    'name_original' => '1.1. Foresight of new and emerging OSH risks  associated with new technologies in green jobs',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 9,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => '00cf9383-d3f2-4220-a8a2-42a0d4b4a33b',
    ),
  );
  $terms[] = array(
    'name' => '4.4. Awareness raising actions',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9a44b23c-2e25-4133-a5a6-200e85a2f3a3',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'raising_awareness_4',
          'format' => NULL,
          'safe_value' => 'raising_awareness_4',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '4.4. Awareness raising actions',
          'format' => NULL,
          'safe_value' => '4.4. Awareness raising actions',
        ),
      ),
    ),
    'name_original' => '4.4. Awareness raising actions',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 24,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => '57c7ff22-5cd8-49c4-8789-262d2a3453bd',
    ),
  );
  $terms[] = array(
    'name' => '7.3. Human Resources',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a45acdc6-c5cd-4590-bd0a-145a80e204e4',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'governance_2',
          'format' => NULL,
          'safe_value' => 'governance_2',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '7.3. Human Resources',
          'format' => NULL,
          'safe_value' => '7.3. Human Resources',
        ),
      ),
    ),
    'name_original' => '7.3. Human Resources',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 34,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => 'f77ff1e1-cccc-4f56-b470-ad638467b135',
    ),
  );
  $terms[] = array(
    'name' => '4.2. Healthy Workplace Campaign (HWC): Healthy Workplaces manage stress',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'abecc2cf-c60c-4be6-8d3d-10d03d051feb',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'raising_awareness_2',
          'format' => NULL,
          'safe_value' => 'raising_awareness_2',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '4.2. Healthy Workplace Campaign (HWC): Healthy Workplaces manage stress',
          'format' => NULL,
          'safe_value' => '4.2. Healthy Workplace Campaign (HWC): Healthy Workplaces manage stress',
        ),
      ),
    ),
    'name_original' => '4.2. Healthy Workplace Campaign (HWC): Healthy Workplaces manage stress',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 22,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => '57c7ff22-5cd8-49c4-8789-262d2a3453bd',
    ),
  );
  $terms[] = array(
    'name' => '2.4. OSH overview : Work-related diseases',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b26d842e-3a43-4f77-a2cc-0d2df9412e29',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'facts_and_figures_4',
          'format' => NULL,
          'safe_value' => 'facts_and_figures_4',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '2.4. OSH overview : Work-related diseases',
          'format' => NULL,
          'safe_value' => '2.4. OSH overview : Work-related diseases',
        ),
      ),
    ),
    'name_original' => '2.4. OSH overview : Work-related diseases',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 15,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => 'e9fa57e4-b0c3-476b-898c-176ae24d6062',
    ),
  );
  $terms[] = array(
    'name' => '6.3. Corporate Communications',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c2c4838f-f565-49d0-8318-d2ad08add644',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'networking_and_corporate_communications_3',
          'format' => NULL,
          'safe_value' => 'networking_and_corporate_communications_3',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '6.3. Corporate Communications',
          'format' => NULL,
          'safe_value' => '6.3. Corporate Communications',
        ),
      ),
    ),
    'name_original' => '6.3. Corporate Communications',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 31,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => '6d67c342-6a54-409f-a512-9796ab5d2fc0',
    ),
  );
  $terms[] = array(
    'name' => '4.3. Healthy Workplace Campaign (HWC): 2016-17',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'cafceb2e-0be4-4e47-ad9a-781b708f58e6',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'raising_awareness_3',
          'format' => NULL,
          'safe_value' => 'raising_awareness_3',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '4.3. Healthy Workplace Campaign (HWC): 2016-17',
          'format' => NULL,
          'safe_value' => '4.3. Healthy Workplace Campaign (HWC): 2016-17',
        ),
      ),
    ),
    'name_original' => '4.3. Healthy Workplace Campaign (HWC): 2016-17',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 23,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => '57c7ff22-5cd8-49c4-8789-262d2a3453bd',
    ),
  );
  $terms[] = array(
    'name' => '6.1. Strategic Networking',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd38c0d0c-fd42-4b0c-ab9d-02cb0e66d6e5',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'networking_and_corporate_communications_1',
          'format' => NULL,
          'safe_value' => 'networking_and_corporate_communications_1',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '6.1. Strategic Networking',
          'format' => NULL,
          'safe_value' => '6.1. Strategic Networking',
        ),
      ),
    ),
    'name_original' => '6.1. Strategic Networking',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 29,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => '6d67c342-6a54-409f-a512-9796ab5d2fc0',
    ),
  );
  $terms[] = array(
    'name' => '8: Operational Management and Support',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd84eb437-a202-4c8b-84c8-537ad1d2c5f5',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'operational_management_and_support',
          'format' => NULL,
          'safe_value' => 'operational_management_and_support',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 1,
          'format' => NULL,
          'safe_value' => 1,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '8: Operational Management and Support',
          'format' => NULL,
          'safe_value' => '8: Operational Management and Support',
        ),
      ),
    ),
    'name_original' => '8: Operational Management and Support',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 36,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '1.2. Large-scale foresight',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e1e5ddc6-1c79-4bf9-8e4a-2f83b12483ef',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'anticipating_change_2',
          'format' => NULL,
          'safe_value' => 'anticipating_change_2',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '1.2. Large-scale foresight',
          'format' => NULL,
          'safe_value' => '1.2. Large-scale foresight',
        ),
      ),
    ),
    'name_original' => '1.2. Large-scale foresight',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 10,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => '00cf9383-d3f2-4220-a8a2-42a0d4b4a33b',
    ),
  );
  $terms[] = array(
    'name' => '2: Facts and figures',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e9fa57e4-b0c3-476b-898c-176ae24d6062',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'facts_and_figures',
          'format' => NULL,
          'safe_value' => 'facts_and_figures',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 1,
          'format' => NULL,
          'safe_value' => 1,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '2: Facts and figures',
          'format' => NULL,
          'safe_value' => '2: Facts and figures',
        ),
      ),
    ),
    'name_original' => '2: Facts and figures',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 11,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '7: Governance',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f77ff1e1-cccc-4f56-b470-ad638467b135',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'governance',
          'format' => NULL,
          'safe_value' => 'governance',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 1,
          'format' => NULL,
          'safe_value' => 1,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '7: Governance',
          'format' => NULL,
          'safe_value' => '7: Governance',
        ),
      ),
    ),
    'name_original' => '7: Governance',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 32,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '7.5. Documentation',
    'description' => NULL,
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'fdfcaba5-538e-42e1-aa7f-0e747e1766bb',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'activity',
    'description_field' => array(),
    'field_activity_code' => array(
      'und' => array(
        0 => array(
          'value' => 'governance_3',
          'format' => NULL,
          'safe_value' => 'governance_3',
        ),
      ),
    ),
    'field_activity_level' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => '7.5. Documentation',
          'format' => NULL,
          'safe_value' => '7.5. Documentation',
        ),
      ),
    ),
    'name_original' => '7.5. Documentation',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 35,
          'language' => 'en',
          'source' => '',
          'uid' => 0,
          'status' => 1,
          'translate' => 0,
          'created' => 1410866602,
          'changed' => 1410866602,
        ),
      ),
    ),
    'description_original' => NULL,
    'metatags' => array(),
    'parent' => array(
      0 => 'f77ff1e1-cccc-4f56-b470-ad638467b135',
    ),
  );
  return $terms;
}
