<?php

define('MIGRATION_TAXONOMY_TAGS', 'TaxonomyTags');
define('MIGRATION_TAXONOMY_ESENER', 'TaxonomyEsener');
define('MIGRATION_TAXONOMY_NACE_CODES', 'TaxonomyNaceCodes');
define('MIGRATION_TAXONOMY_PUBLICATION_TYPES', 'TaxonomyPublicationTypes');
define('MIGRATION_TAXONOMY_THESAURUS', 'TaxonomyThesaurus');
define('MIGRATION_CONTENT_TYPE_NEWS', 'News');

/**
 * You must implement hook_migrate_api(), setting the API level to 2, for
 * your migration classes to be recognized by the Migrate module.
 */
function osha_migration_migrate_api() {
  $migration_module_dir = drupal_get_path('module', 'osha_migration');
  $api = array(
    'api' => 2,
    'migrations' => array(
      MIGRATION_TAXONOMY_NACE_CODES => array(
        'class_name' => 'MigrateOshaTaxonomyNaceCodes',
        'file_name' => $migration_module_dir . '/data/nace_codes.json',
      ),
      MIGRATION_TAXONOMY_ESENER => array(
        'class_name' => 'MigrateOshaTaxonomyEsener',
        'file_name' => $migration_module_dir . '/data/esener.json',
      ),
      MIGRATION_TAXONOMY_PUBLICATION_TYPES => array(
        'class_name' => 'MigrateOshaTaxonomyPublicationTypes',
        'file_name' => $migration_module_dir . '/data/publication_types.json',
      ),
      MIGRATION_TAXONOMY_THESAURUS => array(
        'class_name' => 'MigrateOshaTaxonomyThesaurus',
        'file_name' => $migration_module_dir . '/data/thesaurus.json',
      ),
      MIGRATION_TAXONOMY_TAGS => array(
        'class_name' => 'MigrateOshaTaxonomyTags',
        'file_name' => $migration_module_dir . '/data/tags.json',
      ),
      MIGRATION_CONTENT_TYPE_NEWS => array(
        'class_name' => 'MigrateOshaNews',
        'file_name' => osha_migration_get_data_dir() . '/export/news.txt',
      )
    )
  );
  return $api;
}

/**
 * Implements hook_schema_alter()
 */
function osha_migration_schema_alter(&$schema) {
  if (isset($schema['taxonomy_term_data'])) {
    $schema['taxonomy_term_data']['fields']['name'] = array(
      'type' => 'varchar',
      'length' => 768,
      'not null' => TRUE,
      'default' => '',
    );
  }

  if (isset($schema['field_data_name_field'])) {
    $schema['field_data_name_field']['fields']['name_field_value'] = array(
      'type' => 'varchar',
      'length' => 768,
      'not null' => TRUE,
      'default' => '',
    );
  }

  if (isset($schema['field_revision_name_field'])) {
    $schema['field_revision_name_field']['fields']['name_field_value'] = array(
      'type' => 'varchar',
      'length' => 768,
      'not null' => TRUE,
      'default' => '',
    );
  }
}

/**
 * Retrieve the root directory for the migration data folder
 * @return string|null Path on local disk
 * @throws MigrateException When the variable is empty
 */
function osha_migration_get_data_dir() {
  $ret = variable_get('osha_data_dir', NULL);
  if (empty($ret)) {
    drupal_set_message('Please configure the "osha_data_dir" variable to point to your data storage', 'error');
  }
  return $ret;
}
