<?php

define('MIGRATION_NACE_CODES', 'NaceCodesTest');
define('CLASS_NACE_CODES', 'MigrateOshaNaceCodes');

/**
 * You must implement hook_migrate_api(), setting the API level to 2, for
 * your migration classes to be recognized by the Migrate module.
 */
function osha_migration_migrate_api() {
	$api = array(
		'api' => 2,
		'migrations' => array(
			'News' => array('class_name' => 'MigrateOshaNews'),
            'NaceCodes' => array(
                'class_name' => 'MigrateOshaNaceCodes',
                'file_name' => 'data/nace_codes.json',
                'group_name' => 'OSHA MIGRATIONS'
            ),
			'EsenerTaxonomy' => array('class_name' => 'MigrateOshaEsenerTaxonomy'),
			'PublicationTypesTaxonomy' => array('class_name' => 'MigrateOshaPublicationTypesTaxonomy')
		)
	);
	return $api;
}

/**
 * Implements hook_schema_alter()
 */
function osha_migration_schema_alter(&$schema) {
	if(isset($schema['taxonomy_term_data'])) {
		$schema['taxonomy_term_data']['fields']['name'] = array(
			'type' => 'varchar',
			'length' => 768,
			'not null' => TRUE,
			'default' => '',
		);
	}

	if(isset($schema['field_data_name_field'])) {
		$schema['field_data_name_field']['fields']['name_field_value'] = array(
			'type' => 'varchar',
			'length' => 768,
			'not null' => TRUE,
			'default' => '',
		);
	}

	if(isset($schema['field_revision_name_field'])) {
		$schema['field_revision_name_field']['fields']['name_field_value'] = array(
			'type' => 'varchar',
			'length' => 768,
			'not null' => TRUE,
			'default' => '',
		);
	}
}

/**
 * @return null
 * @throws MigrateException
 */
function osha_migration_get_data_dir() {
	$ret = variable_get('osha_data_dir', NULL);
	if(empty($ret)) {
		throw new MigrateException('Please configure the "osha_data_dir" variable to point to your data storage');
	}
	return $ret;
}
