<?php
/**
 * This template is used to assemble all nodes selected during newsletter
 * creation with Simplenews Content Selection.
 *
 * The following variables are available:
 *    - $toc Table of content, if it exists, as generated by the function
 *    theme_scs_toc() or your own.
 *    - $nodes Array of built selected nodes, ready to be outputed with the
 *    render() function.
 */
?>
<table>
  <tbody>
    <tr>
      <td width="590" valign="top">
        <div style="font: 12px Verdana,Helvetica,'Lucida Grande',Lucida,Arial,sans-serif;">
          <h1 style="color: #191919; font: 18px/35px Verdana,Helvetica,'Lucida Grande',Lucida,Arial,sans-serif; letter-spacing: 2px; margin: 34px 0 11px; text-shadow: 2px 2px 5px #dddddd; text-transform: uppercase;">
            <?php print t('Highlights'); ?>
          </h1>
        </div>
        <?php foreach ($nodes as $node): ?>
          <div style="font: 12px Verdana,Helvetica,'Lucida Grande',Lucida,Arial,sans-serif;">
            <table style="border: 1px solid #d1d1d1; color: #191919; font: 13px/16px Verdana,Helvetica,'Lucida Grande',Lucida,Arial,sans-serif; margin-bottom: 20px; padding: 8px; width: 570px;">
              <tbody>
                <tr>
                  <td colspan="2">
                    <h2 style="color: #191919; font-size: 19px; font-weight: bold; margin: 15px 0; padding: 0 0 11px;">
                      <?php
                      print l($node['#node']->title, url('node/' . $node['field_news_summary']['#object']->nid, array('absolute' => TRUE)), array(
                        'attributes' => array('style' => 'color: #144989; text-decoration: none;'),
                        'external' => TRUE
                      ));
                      ?>
                    </h2>
                  </td>
                </tr>
                <tr>
                  <td width="120" valign="top">
                    <?php
                    print l(theme('image_style', array(
                      'style_name' => 'thumbnail',
                      'path' => $node['field_news_image']['#items'][0]['uri'],
                      'width' => 100,
                      'alt' => $node['field_news_image']['#items'][0]['alt']
                    )), url('node/' . $node['field_news_summary']['#object']->nid, array('absolute' => TRUE)), array(
                      'html' => TRUE,
                      'external' => TRUE
                    ));
                    ?>
                  </td>
                  <td valign="top">
                    <?php print $node['field_news_summary']['#items'][0]['safe_value']; ?>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        <?php endforeach; ?>
        <div style="font: 12px Verdana,Helvetica,'Lucida Grande',Lucida,Arial,sans-serif;">
          <h1 style="border-bottom: 1px dotted #d9d9d9; color: #191919; font: 18px/35px Verdana,Helvetica,'Lucida Grande',Lucida,Arial,sans-serif; letter-spacing: 2px; margin: 34px 0 11px; padding-bottom: 11px; text-shadow: 2px 2px 5px #dddddd; text-transform: uppercase;">
            <?php print t('OSH Matters'); ?>
          </h1>
        </div>
        <div style="font: 12px Verdana,Helvetica,'Lucida Grande',Lucida,Arial,sans-serif;">
          <h1 style="border-bottom: 1px dotted #d9d9d9; color: #191919; font: 18px/35px Verdana,Helvetica,'Lucida Grande',Lucida,Arial,sans-serif; letter-spacing: 2px; margin: 34px 0 11px; padding-bottom: 11px; text-shadow: 2px 2px 5px #dddddd; text-transform: uppercase;">
            <?php print t('Latest Publications'); ?>
          </h1>
        </div>
        <div style="font: 12px Verdana,Helvetica,'Lucida Grande',Lucida,Arial,sans-serif;">
          <h1 style="border-bottom: 1px dotted #d9d9d9; color: #191919; font: 18px/35px Verdana,Helvetica,'Lucida Grande',Lucida,Arial,sans-serif; letter-spacing: 2px; margin: 34px 0 11px; padding-bottom: 11px; text-shadow: 2px 2px 5px #dddddd; text-transform: uppercase;">
            <?php print t('Coming Soon'); ?>
          </h1>
        </div>
      </td>
      <td width="200" valign="top"  style="padding-left: 24px; padding-top: 36px;">
        <div style="font: 12px Verdana,Helvetica,'Lucida Grande',Lucida,Arial,sans-serif;">
          <h2 style="color: #191919; font-size: 18px; font-weight: normal; margin: 12px 0 13px; padding: 0;">
            <?php print t('Blog'); ?>
          </h2>
        </div>
        <div style="background-color: #f2f4f6; font: 12px Verdana,Helvetica,'Lucida Grande',Lucida,Arial,sans-serif; margin-bottom: 20px;">
          <h2 style="color: #191919; font-size: 11px; font-weight: normal; margin-bottom: 13px; padding: 6px 15px; text-align: right;">
            <?php print l(t('View the blog'), 'https://osha.europa.eu/en/about/director_corner/blog', array('attributes' => array('style' => 'color: #144989; text-decoration: none;'), 'external' => TRUE)); ?> &raquo;
          </h2>
        </div>
        <div style="font: 12px Verdana,Helvetica,'Lucida Grande',Lucida,Arial,sans-serif;">
          <h2 style="color: #191919; font-size: 18px; font-weight: normal; margin: 12px 0 13px; padding: 0;">
            <?php print t('News'); ?>
          </h2>
        </div>
        <div style="background-color: #f2f4f6; font: 12px Verdana,Helvetica,'Lucida Grande',Lucida,Arial,sans-serif; margin-bottom: 20px;">
          <h2 style="color: #191919; font-size: 11px; font-weight: normal; margin-bottom: 13px; padding: 6px 15px; text-align: right;">
            <?php print l(t('More news'), 'https://osha.europa.eu/en/news', array('attributes' => array('style' => 'color: #144989; text-decoration: none;'), 'external' => TRUE)); ?> &raquo;
          </h2>
        </div>
        <div style="font: 12px Verdana,Helvetica,'Lucida Grande',Lucida,Arial,sans-serif;">
          <h2 style="color: #191919; font-size: 18px; font-weight: normal; margin: 12px 0 13px; padding: 0;">
            <?php print t('Events'); ?>
          </h2>
        </div>
        <div style="background-color: #dce8f4; font: 12px Verdana,Helvetica,'Lucida Grande',Lucida,Arial,sans-serif; margin-bottom: 20px;">
          <h2 style="color: #191919; font-size: 11px; font-weight: normal; margin-bottom: 13px; padding: 6px 15px; text-align: right;">
            <?php print l(t('More events'), 'https://osha.europa.eu/en/news', array('attributes' => array('style' => 'color: #144989; text-decoration: none;'), 'external' => TRUE)); ?> &raquo;
          </h2>
        </div>
      </td>
    </tr>
  </tbody>
</table>
