<?php
/**
 * @file
 * Code for the Press release feature.
 */

include_once 'osha_press_release.features.inc';

define('OSHA_PRESS_RELEASE_CONTENT_TYPE_PRESS_RELEASE', 'press_release');

/**
 * Implements hook_post_features_enable_feature().
 *
 * {@inheritdoc}
 */
function osha_press_release_post_features_enable_feature($component) {
  // After the field_instance ...
  if ($component == 'variable') {
    menu_rebuild();
    drupal_static_reset();
    if ($role = user_role_load_by_name('administrator')) {
      $permissions = array(
        'create press_release content',
        'edit own press_release content',
        'edit any press_release content',
        'delete own press_release content',
        'delete any press_release content',
      );
      user_role_grant_permissions($role->rid, $permissions);
    }
  }
}
