<?php

define('OSHA_TMGMT_DEFAULT_SOURCE_LANGUAGE', 'en');
define('OSHA_TMGMT_DEFAULT_TARGET_LANGUAGE', 'ro');

/**
 * Implements hook_schema_alter().
 */
function osha_tmgmt_schema_alter(&$schema) {
  if (isset($schema['tmgmt_job_item'])) {
    $schema['tmgmt_job_item']['fields']['target_language'] = array(
      'description' => 'The language the data should be translated to.',
      'type' => 'varchar',
      'size' => 12,
      'default' => '',
      'not null' => TRUE, // TODO: Optional until we fix job_item creation
    );
    $schema['tmgmt_job_item']['fields']['source_language'] = array(
      'description' => 'The default entity language',
      'type' => 'varchar',
      'size' => 12,
      'default' => '',
      'not null' => TRUE, // TODO: Optional until we fix job_item creation
    );
  }
}

/**
 * Implements hook_tmgmt_file_format_info().
 */
function osha_tmgmt_tmgmt_file_format_plugin_info() {
  return array(
    'xml' => array(
      'label' => t('CDT XML file'),
      'plugin controller class' => 'OSHATranslatorFileformatCDT',
    ),
  );
}


/**
 * Implements hook_entity_info_alter().
 */
function osha_tmgmt_entity_info_alter(&$entity_info) {
  if (isset($entity_info['tmgmt_job_item'])) {
    $entity_info['tmgmt_job_item']['views controller class'] = 'TMGMTOshaJobItemViewsController';
  }
}

/**
 * Implements hook_menu_alter().
 *
 * Removes tmgmt unwanted menu items
 */
function osha_tmgmt_menu_alter(&$items) {
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function osha_tmgmt_form_tmgmt_ui_cart_content_alter(&$form, &$form_state, $form_id) {
  $form['request_translation']['#submit'] = array('osha_tmgmt_tmgmt_ui_cart_content_submit');
}

/**
 * Overrides form submit for tmgmt cart checkout.
 */
function osha_tmgmt_tmgmt_ui_cart_content_submit($form, &$form_state) {
  global $user;
  $job_empty = TRUE;
  $target_languages = array_filter($form_state['values']['target_language']);

  $job_items_by_source_language = array();
  // Group the selected items by source language.
  foreach (tmgmt_job_item_load_multiple(array_filter($form_state['values']['items'])) as $job_item) {
    $job_items_by_source_language[$job_item->getSourceLangCode()][$job_item->tjiid] = $job_item;
  }

  $job = tmgmt_job_create(
    OSHA_TMGMT_DEFAULT_SOURCE_LANGUAGE,
    OSHA_TMGMT_DEFAULT_TARGET_LANGUAGE,
    $user->uid
  );

  $remove_job_item_ids = array();
  // Loop over all target languages, create a job for each source and target
  // language combination add add the relevant job items to it.
  foreach ($target_languages as $target_language) {
    $job_empty = TRUE;
    foreach ($job_items_by_source_language as $source_language => $job_items) {
      // Skip in case the source language is the same as the target language.
      if ($source_language == $target_language) {
        continue;
      }
      /* @var TMGMTJobItem $job_item */
      foreach ($job_items as $id => $job_item) {
        try {
          // As the same item might be added to multiple jobs, we need to
          // re-create them and delete the old ones, after removing them from
          // the cart.
          $new_job_item = $job->addItem($job_item->plugin, $job_item->item_type, $job_item->item_id);
          $new_job_item->source_language = $source_language;
          $new_job_item->target_language = $target_language;
          $new_job_item->save();
          $remove_job_item_ids[$job_item->tjiid] = $job_item->tjiid;
          $job_empty = FALSE;
        }
        catch (Exception $e) {
          // If an item fails for one target language, then it is also going
          // to fail for others, so remove it from the array.
          unset($job_items_by_source_language[$source_language][$id]);
          drupal_set_message($e->getMessage(), 'error');
        }
      }
    }
  }
  if (!$job_empty) {
    // Remove assigned job items from the cart.
    if ($remove_job_item_ids) {
      tmgmt_ui_cart_get()->removeJobItems($remove_job_item_ids);
      entity_delete_multiple('tmgmt_job_item', $remove_job_item_ids);
    }
    if ($job) {
      // Start the checkout process if any jobs were created.
      tmgmt_ui_job_checkout_and_redirect($form_state, array($job));
    }
  }
  else {
    //TODO: Delete the job ...?
  }
}

function osha_tmgmt_views_default_views_alter(&$views) {
  if(isset($views['tmgmt_ui_job_items'])) {
    $handler =& $views['tmgmt_ui_job_items']->display['submit'];

    /* Field: Translation Management Job Item: Source language */
    $handler->display_options['fields']['source_language']['id'] = 'source_language';
    $handler->display_options['fields']['source_language']['table'] = 'tmgmt_job_item';
    $handler->display_options['fields']['source_language']['field'] = 'source_language';

    /* Field: Translation Management Job Item: Target language */
    $handler->display_options['fields']['target_language']['id'] = 'target_language';
    $handler->display_options['fields']['target_language']['table'] = 'tmgmt_job_item';
    $handler->display_options['fields']['target_language']['field'] = 'target_language';

    // Move operations field last.
    $operations = $handler->display_options['fields']['operations'];
    unset($handler->display_options['fields']['operations']);
    $handler->display_options['fields']['operations'] = $operations;
  }
  if(isset($views['tmgmt_ui_job_overview'])) {
    $handler =& $views['tmgmt_ui_job_overview']->display['default'];
    unset($handler->display_options['filters']['source_language']);
    unset($handler->display_options['filters']['target_language']);
    unset($handler->display_options['filters']['translator']);
  }
}
