<?php

/**
 * Implements hook_install().
 *
 * Disable drupal default blocks.
 */
function osha_frontend_install() {
  db_update('block')
    ->fields(array('status' => 0))
    ->condition('module', 'system')
    ->condition('delta', 'navigation')
    ->condition('theme', 'osha_frontend')
    ->execute();

  db_update('block')
    ->fields(array('status' => 0))
    ->condition('module', 'user')
    ->condition('delta', 'login')
    ->condition('theme', 'osha_frontend')
    ->execute();
}
