<?php
/**
 * @file
 * Code for the osha_content_edw feature.
 */

include_once 'osha_content_edw.features.inc';

/**
 * Implements hook_uuid_node_features_rebuild().
 * Allows cleaning up nids from path_alias/source
 */
function osha_content_edw_uuid_node_features_rebuild_alter(&$node, $module) {
  // Workbench integration.
  if (!empty($node->workbench_moderation)) {
    if (!empty($node->workbench_moderation['published']['published'])) {
      $node->workbench_moderation_state_new = 'published';
    }
    unset($node->workbench_moderation);
  }
  unset($node->path['source']);
  unset($node->path['pid']);
}
