<?php

/**
 * Implements hook_field_info().
 */
function osha_slideshare_field_info() {
  return array(
    'slideshare' => array(
      'label' => t('Slideshare URL'),
      'description' => t('This field add a slideshare link'),
      'default_widget' => 'slideshare_field',
      'default_formatter' => 'slideshare_default',
    ),
  );
}

/**
 * Implements hook_field_widget_info().
 */
function osha_slideshare_field_widget_info() {
  return array(
    'slideshare' => array(
      'label' => t('Slideshare'),
      'field types' => array('slideshare'),
    ),
  );
}

/**
 * Implements hook_field_settings_form().
 */
function osha_slideshare_field_settings_form($field, $instance, $has_data) {
  $settings = $field['settings'];
  // Add your global settings fields here
  $form['api_key'] = array(
    '#type' => 'textfield',
    '#title' => 'Slideshare API Key',
    '#default_value' => isset($settings['api_key'])? $settings['api_key']: '6WKMTITI'
  );

  $form['secret_key'] = array(
    '#type' => 'textfield',
    '#title' => 'Slideshare Secret Key',
    '#default_value' => isset($settings['secret_key'])? $settings['secret_key']: 'v1HYiYhg'
  );

  return $form;
}

/**
 * Implements hook_field_instance_settings_form().
 */
function osha_slideshare_field_instance_settings_form($field, $instance) {
  $settings = $instance['settings'];
  // Add your instance settings fields here.
  $form = array();
  return $form;
}

/**
 * Implements hook_field_widget_form().
 */
function osha_slideshare_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $element['slide_url'] = $element + array(
    '#type' => 'textfield',
    '#title' => t('Slideshare URL'),
    '#default_value' => isset($items[$delta]['slide_url']) ? $items[$delta]['slide_url'] : '',
    '#attributes' => array('maxlength' => 256),
  );

  if($element['#description'] == '') {
    $element['slide_url']['#description'] = t('Enter the Slideshare URL. Valid URL
      format like: http://www.slideshare.net/euosha/hwc-esener');
  }

  return $element;
}

/**
 * Implements hook_field_validate().
 */
function osha_slideshare_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  // Loop through field items in the case of multiple values.
  foreach ($items as $delta => $item) {
    if (isset($item['slide_url']) && $item['slide_url'] != '') {
      if (!valid_slide_url($item['slide_url'])) {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'slide_url_invalid',
          'message' => t('Invalid Slideshare URL.'),
        );
      }
    }
  }
}

function valid_slide_url($url){
  $pattern = '/(http:\/\/)www\.slideshare\.net\/([\w\d-_\/]+)/';

  if(valid_url($url) && preg_match($pattern, $url)){
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_field_is_empty().
 */
function osha_slideshare_field_is_empty($item, $field) {
  return empty($item['slide_url']);
}

/**
 * Implements hook_field_formatter_info().
 */
function osha_slideshare_field_formatter_info() {
  return array(
    'slideshare_default' => array(
      'label' => t('Default'),
      'field types' => array('slideshare'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function osha_slideshare_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'slideshare_default' :
      foreach ($items as $delta => $item) {
        if (isset($item['slide_url'])) {
          $element[$delta]['#markup'] =
            getSlideshareInfos($field['settings']['api_key'], $field['settings']['secret_key'], $item['slide_url']);
        }
      }
      break;
  }
  return $element;
}

/**
 * Implements hook_theme
 */
function osha_slideshare_theme(){
  $theme = array();
  $path = drupal_get_path('module', 'osha_slideshare');

  $theme['slideshare_display'] = array(
    'template' => 'slideshare_display',
    'variables' => array(
      'xml' => NULL
    ),
    'path' => $path . '/templates',
  );

  return $theme;
}

/**
 * Connect to Slideshare and get information
 * about the URL provided
 */
function getSlideshareInfos($api_key, $secret_key, $slideshow_url){
  $url = 'https://www.slideshare.net/api/2/get_slideshow';
  $ts = time();
  $hash = sha1($secret_key.$ts);
  $params = 'api_key='.$api_key.'&ts='.$ts.'&hash='.$hash.'&slideshow_url='.$slideshow_url;

  $url = $url.'?'.$params;

  $request = drupal_http_request($url);
  $xml = simplexml_load_string($request->data);

  return theme('slideshare_display',array('xml' => $xml));
}
