<?php
/**
 * @file
 * Code for the Calls feature.
 */

include_once 'osha_calls.features.inc';

define('OSHA_CALLS_CONTENT_TYPE_CALLS', 'calls');

/**
 * Implements hook_post_features_enable_feature().
 *
 * {@inheritdoc}
 */
function osha_calls_post_features_enable_feature($component) {
  // After the field_instance ...
  if ($component == 'variable') {
    menu_rebuild();
    drupal_static_reset();
    if ($role = user_role_load_by_name('administrator')) {
      $permissions = array(
        'create calls content',
        'edit own calls content',
        'edit any calls content',
        'delete own calls content',
        'delete any calls content',
      );
      user_role_grant_permissions($role->rid, $permissions);
    }
  }
}
