<?php
/**
 * @file
 * Code for the News feature.
 */

include_once 'osha_news.features.inc';

define('OSHA_NEWS_CONTENT_TYPE_NEWS', 'news');

/**
 * Implements hook_post_features_enable_feature().
 *
 * {@inheritdoc}
 */
function osha_news_post_features_enable_feature($component) {
  // After the field_instance ...
  if ($component == 'variable') {
    menu_rebuild();
    drupal_static_reset();
    if ($role = user_role_load_by_name('administrator')) {
      $permissions = array(
        'create news content',
        'edit own news content',
        'edit any news content',
        'delete own news content',
        'delete any news content',
      );
      user_role_grant_permissions($role->rid, $permissions);
    }
  }
}


function osha_news_workbench_access_node_element_alter(&$element, $form_state, $active) {
  if (isset($form_state['build_info']['form_id']) && $form_state['build_info']['form_id'] == 'news_node_form' ) {
    // CW-800 default value for Section
    $element['#required'] = FALSE;
    foreach ($element['#options'] as $key=>$option) {
      if (preg_match('/^[-\\s]*Home/', $option)) {
        $element['#default_value'] = $key;
        break;
      }
    }
  }
}
