<?php
/**
 * @file
 * Code for the Blog feature.
 */

include_once 'osha_blog.features.inc';

define('OSHA_BLOG_CONTENT_TYPE_BLOG', 'blog');

/**
 * Implements hook_post_features_enable_feature().
 *
 * {@inheritdoc}
 */
function osha_blog_post_features_enable_feature($component) {
  // After the field_instance ...
  if ($component == 'variable') {
    menu_rebuild();
    drupal_static_reset();
    if ($role = user_role_load_by_name('administrator')) {
      $permissions = array(
        'create blog content',
        'edit own blog content',
        'edit any blog content',
        'delete own blog content',
        'delete any blog content',
      );
      user_role_grant_permissions($role->rid, $permissions);
    }
  }

  //Add recaptcha validation for blog comment form
  $data = array(
    'form_id' => 'comment_node_blog_form',
    'module' => 'recaptcha',
    'captcha_type' => 'reCAPTCHA',
  );
  drupal_write_record('captcha_points', $data, 'form_id');
}
