<?php
/**
 * @file
 * Drupal needs this blank file.
 */


function osha_configure_entity_translation_types() {
	variable_set(
		'entity_translation_entity_types',
		array(
			'node' => 'node',
			'taxonomy_term' => 'taxonomy_term',
			'comment' => 0,
			'user' => 0,
		)
	);
}

function osha_configure_language_detection() {
	module_load_include('inc', 'locale', 'locale.admin');

	$form_state['values']['language']['enabled']['locale-url'] = 1;
	$form_state['values']['language']['weight']['locale-url'] = -8;

	$form_state['values']['language']['enabled']['language-default'] = 1;
	$form_state['values']['language']['weight']['language-default'] = 10;


	$form_state['values']['language_content']['enabled']['locale-url'] = 1;
	$form_state['values']['language_content']['weight']['locale-url'] = -8;

	$form_state['values']['language_content']['enabled']['language-default'] = 1;
	$form_state['values']['language_content']['weight']['language-default'] = 10;

	drupal_form_submit('locale_languages_configure_form', $form_state);
}