<?php
/**
 * @file
 * Code for the osha feature.
 */

include_once 'osha.features.inc';

// You can find it using drush vget, saved by install.sh script
define('OSHA_CONFIG_VARIABLE', 'osha_config');

function osha_configure_entity_translation_types() {
	variable_set(
		'entity_translation_entity_types',
		array(
			'node' => 'node',
			'taxonomy_term' => 'taxonomy_term',
			'comment' => 0,
			'user' => 0,
		)
	);
}

function osha_configure_language_detection() {
	module_load_include('inc', 'locale', 'locale.admin');

	$form_state['values']['language']['enabled']['locale-url'] = 1;
	$form_state['values']['language']['weight']['locale-url'] = -8;

	$form_state['values']['language']['enabled']['language-default'] = 1;
	$form_state['values']['language']['weight']['language-default'] = 10;


	$form_state['values']['language_content']['enabled']['locale-url'] = 1;
	$form_state['values']['language_content']['weight']['locale-url'] = -8;

	$form_state['values']['language_content']['enabled']['language-default'] = 1;
	$form_state['values']['language_content']['weight']['language-default'] = 10;

	drupal_form_submit('locale_languages_configure_form', $form_state);
}

/**
 * Function to retrive the size of a MySQL varchar column from a table
 * @param string $table Table name
 * @param string $column Target column
 * @return int
 */
function osha_get_mysql_column_size($table, $column) {
	$result = db_query("
		SELECT CHARACTER_MAXIMUM_LENGTH
		FROM information_schema.columns
		WHERE table_schema = DATABASE()
			AND table_name = :table AND COLUMN_NAME = :column",
		array(':table' => $table, ':column' => $column)
	);
	return $result->fetchField(0);
}
