<?php
/**
 * @file
 * Code for the osha feature.
 */

include_once 'osha.features.inc';

function osha_form_field_ui_field_edit_form_alter(&$form, &$form_state) {
  //dpm($form_state);
}

function osha_configure_date_settings() {
  /* Set default country, first day of the month and date format */
  variable_set('date_first_day', '1');
  variable_set('site_default_country', 'ES');
  variable_set('date_default_timezone', 'Europe/Madrid');
  variable_set('configurable_timezones', '0');
  variable_set('user_default_timezone', '0');
}

function osha_configure_entity_translation() {
  // /admin/config/regional/entity_translation
  if (!module_load_include('inc', 'entity_translation', 'entity_translation.admin')) {
    throw new Exception('module_load_include: entity_translation.admin.inc: No such file or directory');
  }

  $form_state = array();

  $form_state['values']['locale_field_language_fallback'] = 1;
  $form_state['values']['entity_translation_settings_node__article']['default_language'] = ENTITY_TRANSLATION_LANGUAGE_DEFAULT;
  $form_state['values']['entity_translation_settings_node__page']['default_language'] = ENTITY_TRANSLATION_LANGUAGE_DEFAULT;

  drupal_form_submit('entity_translation_admin_form', $form_state);

  $errors = form_get_errors();

  if (!empty($errors)) {
    foreach ($errors as $error) {
      $msg = 'Error: %error';
      $var = array('%error' => $error);

      watchdog('osha.module.install', $msg, $var, WATCHDOG_ERROR);
    }
  }
}

function osha_configure_entity_translation_types() {
  variable_set(
    'entity_translation_entity_types',
    array(
      'node' => 'node',
      'taxonomy_term' => 'taxonomy_term',
      'comment' => 0,
      'user' => 0,
    )
  );
}

function osha_configure_language_detection() {
  module_load_include('inc', 'locale', 'locale.admin');

  $form_state['values']['language']['enabled']['locale-url'] = 1;
  $form_state['values']['language']['weight']['locale-url'] = -8;

  $form_state['values']['language']['enabled']['language-default'] = 1;
  $form_state['values']['language']['weight']['language-default'] = 10;


  $form_state['values']['language_content']['enabled']['locale-url'] = 1;
  $form_state['values']['language_content']['weight']['locale-url'] = -8;

  $form_state['values']['language_content']['enabled']['language-default'] = 1;
  $form_state['values']['language_content']['weight']['language-default'] = 10;

  drupal_form_submit('locale_languages_configure_form', $form_state);
}


/**
 * Function to retrive the size of a MySQL varchar column from a table
 * @param string $table Table name
 * @param string $column Target column
 * @return int
 */
function osha_get_mysql_column_size($table, $column) {
  $result = db_query("
		SELECT CHARACTER_MAXIMUM_LENGTH
		FROM information_schema.columns
		WHERE table_schema = DATABASE()
			AND table_name = :table AND COLUMN_NAME = :column",
    array(':table' => $table, ':column' => $column)
  );
  return $result->fetchField(0);
}

function osha_replace_title_field() {
  if (!module_load_include('module', 'title', 'title')) {
    throw new Exception('Cannot load title.module.inc');
  }
  $types = array(
    'article',
    'page'
  );
  foreach ($types as $bundle) {
    // Inspired from https://www.drupal.org/files/1801242-title-upgrade.patch
    title_field_replacement_toggle('node', $bundle, 'title');
    // We don't need batch processing here, there is no content at this stage
    drupal_set_message(
      t("Replacing title_field for !bundle", array('!bundle' => $bundle))
    );
  }
}

function osha_configure_article() {
  if (!module_load_include('inc', 'node', 'content_types')) {
    throw new Exception('Cannot load content_types.inc');
  }
  $form_state['values']['language_content_type'] = ENTITY_TRANSLATION_ENABLED;
  $form_state['values']['entity_translation_hide_translation_links'] = 1;
  $form_state['values']['promote'] = NULL;
  $form_state['values']['comment'] = 1;
  $type = node_type_load('article');
  drupal_form_submit('node_type_form', $form_state, $type);
  $errors = form_get_errors();
  if (!empty($errors)) {
    foreach ($errors as $error) {
      drupal_set_message(
        t("Article setup error: !error", array('!error' => $error))
      );
    }
  }
}

function osha_configure_basic_page() {
  if (!module_load_include('inc', 'node', 'content_types')) {
    throw new Exception('Cannot load content_types.inc');
  }
  $form_state['values']['language_content_type'] = ENTITY_TRANSLATION_ENABLED;
  $form_state['values']['entity_translation_hide_translation_links'] = 1;
  $form_state['values']['promote'] = NULL;
  $form_state['values']['comment'] = 1;
  $type = node_type_load('page');
  drupal_form_submit('node_type_form', $form_state, $type);
  $errors = form_get_errors();
  if (!empty($errors)) {
    foreach ($errors as $error) {
      drupal_set_message(
        t("Basic page setup error: !error", array('!error' => $error))
      );
    }
  }
}

function osha_enable_body_translations() {
  if (!module_load_include('inc', 'entity_translation', 'entity_translation.admin')) {
    throw new Exception('Cannot load content_types.inc');
  }
  $info = field_info_field('body');
  if ($info !== NULL) { // During tests, body may not be available
    drupal_set_message(t("Making body field translatable"));
    $form_state['values']['translatable'] = "0";
    $form_state['field']['field_name'] = 'body';
    drupal_form_submit('entity_translation_translatable_form', $form_state, 'body');
  }
  else {
    drupal_set_message(t("Body field not available yet"), 'error');
  }
}
