<?php
/**
 * @file
 * Code for the Seminar feature.
 */

include_once 'osha_seminar.features.inc';

define('OSHA_SEMINAR_CONTENT_TYPE_SEMINAR', 'seminar');

/**
 * Implements hook_post_features_enable_feature().
 *
 * {@inheritdoc}
 */
function osha_seminar_post_features_enable_feature($component) {
  // After the field_instance ...
  if ($component == 'variable') {
    menu_rebuild();
    drupal_static_reset();
    if ($role = user_role_load_by_name('administrator')) {
      $permissions = array(
        'create seminar content',
        'edit own seminar content',
        'edit any seminar content',
        'delete own seminar content',
        'delete any seminar content',
      );
      user_role_grant_permissions($role->rid, $permissions);
    }
  }
}

function osha_seminar_workbench_access_node_element_alter(&$element, $form_state, $active) {
  if (isset($form_state['build_info']['form_id']) && $form_state['build_info']['form_id'] == 'seminar_node_form' ) {
    // CW-865 default value for Section
    $element['#required'] = FALSE;
    foreach ($element['#options'] as $key=>$option) {
      if (preg_match('/^[-\\s]*Our seminars/', $option)) {
        $element['#default_value'] = $key;
        break;
      }
    }
  }
}

/**
 * Implements hook_field_formatter_info().
 */
function osha_seminar_field_formatter_info() {
  $info = array(
    'field_related_resources' => array(
      'label' => 'Seminar related resources',
      'field types' => array('file'),
      'description' => 'Displays default icon per file type and file description.',
    ),
  );
  return $info;
}

/**
 * Implements hook_theme().
 */
function osha_seminar_theme() {
  return array(
    'osha_seminar_file_related_resources_format' => array(
      'variables' => array('file' => NULL, 'delta' => NULL),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function osha_seminar_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'field_related_resources':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#theme' => 'osha_seminar_file_related_resources_format',
          '#file' => $item,
          '#delta' => $delta,
        );
      }
      break;
  }
  return $element;
}

/*
 * Formats the related resources (attached files) as icon and description/filename
 */
function theme_osha_seminar_file_related_resources_format($element) {
  $file = (object) $element['file'];
  $icon_directory = drupal_get_path('theme', 'osha_frontend') . '/images/file_icons';

  $name = ($file->description != NULL) ? $file->description : $file->filename;
  $output = '<a href="' . file_create_url($file->uri) . '">';
  $output .= theme('file_icon', array('file' => $file, 'icon_directory' => $icon_directory));
  $output .= '<span>'.$name.'</span>';
  $size = @filesize($file->uri);
  if ($size) {
    $output .= '<span>' . format_size($size) . '</span>';
  }
  $output .= '</a>';

  return $output;
}