<?php

/**
 * Implements hook_entity_info().
 */
function osha_alert_service_entity_info() {
  $info = array();
  $info['osha_alert_service'] = array(
    'label' => t('OSHA Alert'),
    'base table' => 'osha_alert_service',
    'entity keys' => array(
      'id' => 'id',
    ),
    'module' => 'osha_alert_service',
    'entity class' => 'Entity',
    'controller class' => 'EntityAPIController',
  );
  return $info;
}

/**
 * Implements hook_block_info().
 */
function osha_alert_service_block_info() {
  $path = drupal_lookup_path('source', 'alertservice');
  $pages = 'alertservice';
  if ($node = menu_get_object('node', 1, $path)) {
    $pages .= "\r\nnode/" . $node->nid;
  }
  $pages_unsubscribe = 'alertservice/unsubscribe';
  if ($node = menu_get_object('node', 1, $path)) {
    $pages_unsubscribe .= "\r\nnode/" . $node->nid;
  }
  return array(
    'osha_alert_service_subscribe' => array(
      'info' => 'Alert Service Subscription',
      'cache' => DRUPAL_CACHE_GLOBAL,
      'status' => 1,
      'region' => 'content',
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => $pages,
    ),
    'osha_alert_service_unsubscribe' => array(
      'info' => 'Unsubscribe from the alert service',
      'cache' => DRUPAL_CACHE_GLOBAL,
      'status' => 1,
      'region' => 'content',
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => $pages_unsubscribe,
    ),
  );
}

/**
 * Implements hook_block_view().
 *
 * {@inheritdoc}
 */
function osha_alert_service_block_view($delta = '') {
  $ret = array();
  switch ($delta) {
    case 'osha_alert_service_subscribe':
      $form = drupal_get_form('osha_alert_service_subscribe_form');
      $ret['content'] = array(
        '#type' => 'item',
        '#markup' => drupal_render($form),
      );
      break;

    case 'osha_alert_service_unsubscribe':
      $form = drupal_get_form('osha_alert_service_unsubscribe_form');
      $ret['content'] = array(
        '#type' => 'item',
        '#markup' => drupal_render($form),
      );
      break;
  }
  return $ret;
}

function osha_alert_service_subscribe_form($form, $form_state) {
  $form = array(
    '#tree' => FALSE,
  );
  global $user;
  $email = '';
  if (!empty($user->mail)) {
    $email = $user->mail;
  }
  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mail'),
    '#default_value' => $email,
    '#required' => TRUE,
  );

  $sections = workbench_access_active_options();
  // $tree = workbench_access_get_active_tree();
  // $sections = array();
  $form['section'] = array(
    '#type' => 'select',
    '#multiple' => TRUE, '#size' => 10,
    '#title' => t('Subjects of interest'),
    '#required' => TRUE,
    '#options' => $sections,
  );

  $types = array();
  $alltypes = node_type_get_types();
  foreach ($alltypes as $machine_name => $type) {
    $types[$machine_name] = $type->name;
  }
  $form['type'] = array(
    '#type' => 'select',
    '#multiple' => TRUE, '#size' => 10,
    '#title' => t('Item type'),
    '#required' => TRUE,
    '#options' => $types,
  );

  $form['schedule'] = array(
    '#type' => 'select',
    '#multiple' => FALSE,
    '#title' => t('Item type'),
    '#options' => array(
      'daily' => t('Daily'),
      'weekly' => t('Weekly'),
      'monthly' => t('Monthly'),
    ),
    '#default_value' => 'monthly',
  );

  $languages = array();
  $alllanguages = language_list();
  unset($alllanguages['en']);
  foreach ($alllanguages as $code => $language) {
    $languages[$code] = $language->native;
  }
  $form['languages'] = array(
    '#type' => 'select',
    '#multiple' => TRUE, '#size' => 10,
    '#title' => t('Additional languages'),
    '#options' => $languages,
    '#description' => t('Alerts are sent in English. If the content is translated, you can choose to receive it in additional languages.'),
  );

  $form['help'] = array(
    '#type' => 'item',
    '#markup' => t('<b>Note</b>: In order to choose more than one item from the list, press the key CTRL on your keyboard (CMD on Mac), and select the item with your mouse.'),
  );

  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#name' => 'subscribe',
    '#value' => t('Subscribe'),
    '#attributes' => array('class' => array('container-inline')),
  );
  return $form;
}

/**
 * Implements hook_form_validate().
 *
 * {@inheritdoc}
 */
function osha_alert_service_subscribe_form_validate($form, $form_state) {
  if (empty($form_state['values']['email']) || !valid_email_address($form_state['values']['email'])) {
    form_set_error('email', t('Please input an valid email address'));
  };
}

/**
 * Implements hook_form_submit().
 *
 * {@inheritdoc}
 */
function osha_alert_service_subscribe_form_submit($form, $form_state) {
  $values = $form_state['values'];
  $filters = array(
    'section' => array_values($values['section']),
    'type' => array_values($values['type']),
    'languages' => array_values($values['languages']),
  );
  $created = time();
  $email = $values['email'];
  $token = sha1('TIMESTAMP:' . $created);
  $entity = entity_create(
    'osha_alert_service',
    array(
      'email' => $email,
      'filters' => json_encode($filters),
      'schedule' => $values['schedule'],
      'created' => $created,
      'token' => $token,
      'confirmed' => 0,
      'last_alert' => NULL,
    )
  );
  entity_save('osha_alert_service', $entity);
  drupal_set_message(t('Your request has been registered. Please check your email for further instructions'));

  global $language;
  $params = array(
    'email' => $email,
    'token' => $token,
    'language' => $language->language,
  );
  drupal_mail('osha_alert_service', 'subscribe', $email, $language->language, $params);
}

function osha_alert_service_unsubscribe_form($form, $form_state) {
  $form = array(
    '#tree' => FALSE,
  );
  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mail'),
    '#default_value' => '',
    '#required' => TRUE,
  );
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#name' => 'subscribe',
    '#value' => t('Unsubscribe'),
    '#attributes' => array('class' => array('container-inline')),
  );
  return $form;
}

function osha_alert_service_unsubscribe_form_submit($form, $form_state) {

}


/**
 * Implements hook_mail().
 *
 * {@inheritdoc}
 */
function osha_alert_service_mail($key, &$message, $params) {
  $keys = array();
  foreach ($params as $k => $v) {
    $keys[] = '[' . $k . ']';
  }
  switch ($key) {
    case 'subscribe':
      $subject = variable_get('osha_mail_template_alert_service_subscribe_subject', 'Your subscription to OSHA Alert Service');
      $body = variable_get('osha_mail_template_alert_service_subscribe_body',
<<<EOT
EU-OSHA received a request to start sending alerts to [email].

Verify this EU-OSHA alert request: https://osha.europa.eu/alertservice/verify_alert?token=[token]
Cancel this EU-OSHA alert request: https://osha.europa.eu/alertservice/remove_alert?token=[token]
If you are not able to click on the link, you can cut and paste it into your browser's address bar.

If you did not initiate this request or believe it was sent in error you can safely ignore this message.
Thanks,
The EU-OSHA Alerts Team
EOT
      );
      $message['subject'] = $subject;
      $message['body'] = str_replace($keys, array_values($params), $body);
      break;

    case 'unsubscribe':
      $subject = variable_get('osha_mail_template_alert_service_unsubscribe_subject', 'Unsubscribe from OSHA Alert Service');
      $body = variable_get('osha_mail_template_alert_service_unsubscribe_body',
        <<<EOT
        EU-OSHA received a request to cancel alerts sent to [email].

Cancel this EU-OSHA alert request: https://osha.europa.eu/alertservice/remove_alert?token=[token]
If you are not able to click on the link, you can cut and paste it into your browser's address bar.

If you did not initiate this request or believe it was sent in error you can safely ignore this message.
Thanks,
The EU-OSHA Alerts Team
EOT
      );
      $message['subject'] = $subject;
      $message['body'] = str_replace(array_keys($params), array_values($params), $body);
      break;
  }
}
